(grasp right shot14)
(fill-shot shot14 ingredient3 right left dispenser3)
(pour-shot-to-clean-shaker shot14 ingredient3 shaker1 right l0 l1)
(clean-shot shot14 ingredient3 right left)
(fill-shot shot14 ingredient2 right left dispenser2)
(pour-shot-to-used-shaker shot14 ingredient2 shaker1 right l1 l2)
(clean-shot shot14 ingredient2 right left)
(fill-shot shot14 ingredient3 right left dispenser3)
(leave right shot14)
(grasp right shaker1)
(shake cocktail6 ingredient2 ingredient3 shaker1 right left)
(pour-shaker-to-shot cocktail6 shot6 right shaker1 l2 l1)
(leave right shaker1)
(grasp right shot12)
(fill-shot shot12 ingredient2 right left dispenser2)
(grasp left shot13)
(leave right shot12)
(fill-shot shot13 ingredient3 left right dispenser3)
(grasp right shot15)
(leave left shot13)
(fill-shot shot15 ingredient1 right left dispenser1)
(grasp left shaker1)
(leave right shot15)
(empty-shaker left shaker1 cocktail6 l1 l0)
(clean-shaker left right shaker1)
(grasp right shot15)
(pour-shot-to-clean-shaker shot15 ingredient1 shaker1 right l0 l1)
(leave left shaker1)
(clean-shot shot15 ingredient1 right left)
(fill-shot shot15 ingredient5 right left dispenser5)
(pour-shot-to-used-shaker shot15 ingredient5 shaker1 right l1 l2)
(leave right shot15)
(grasp right shaker1)
(shake cocktail1 ingredient1 ingredient5 shaker1 right left)
(pour-shaker-to-shot cocktail1 shot8 right shaker1 l2 l1)
(empty-shaker right shaker1 cocktail1 l1 l0)
(clean-shaker right left shaker1)
(grasp left shot12)
(pour-shot-to-clean-shaker shot12 ingredient2 shaker1 left l0 l1)
(leave right shaker1)
(clean-shot shot12 ingredient2 left right)
(fill-shot shot12 ingredient1 left right dispenser1)
(pour-shot-to-used-shaker shot12 ingredient1 shaker1 left l1 l2)
(clean-shot shot12 ingredient1 left right)
(fill-shot shot12 ingredient2 left right dispenser2)
(grasp right shaker1)
(leave left shot12)
(shake cocktail8 ingredient1 ingredient2 shaker1 right left)
(pour-shaker-to-shot cocktail8 shot10 right shaker1 l2 l1)
(empty-shaker right shaker1 cocktail8 l1 l0)
(clean-shaker right left shaker1)
(grasp left shot12)
(pour-shot-to-clean-shaker shot12 ingredient2 shaker1 left l0 l1)
(leave right shaker1)
(clean-shot shot12 ingredient2 left right)
(fill-shot shot12 ingredient5 left right dispenser5)
(pour-shot-to-used-shaker shot12 ingredient5 shaker1 left l1 l2)
(clean-shot shot12 ingredient5 left right)
(fill-shot shot12 ingredient1 left right dispenser1)
(grasp right shot14)
(empty-shot right shot14 ingredient3)
(leave left shot12)
(clean-shot shot14 ingredient3 right left)
(fill-shot shot14 ingredient5 right left dispenser5)
(grasp left shot13)
(leave right shot14)
(grasp right shaker1)
(empty-shot left shot13 ingredient3)
(leave left shot13)
(shake cocktail5 ingredient2 ingredient5 shaker1 right left)
(pour-shaker-to-shot cocktail5 shot7 right shaker1 l2 l1)
(grasp left shot12)
(leave right shaker1)
(empty-shot left shot12 ingredient1)
(clean-shot shot12 ingredient1 left right)
(fill-shot shot12 ingredient2 left right dispenser2)
(grasp right shot14)
(leave left shot12)
(empty-shot right shot14 ingredient5)
(clean-shot shot14 ingredient5 right left)
(fill-shot shot14 ingredient3 right left dispenser3)
(grasp left shot11)
(leave right shot14)
(fill-shot shot11 ingredient1 left right dispenser1)
(grasp right shot15)
(leave left shot11)
(refill-shot shot15 ingredient5 right left dispenser5)
(grasp left shaker1)
(empty-shaker left shaker1 cocktail5 l1 l0)
(leave right shot15)
(clean-shaker left right shaker1)
(grasp right shot11)
(pour-shot-to-clean-shaker shot11 ingredient1 shaker1 right l0 l1)
(leave right shot11)
(grasp right shot12)
(pour-shot-to-used-shaker shot12 ingredient2 shaker1 right l1 l2)
(leave right shot12)
(shake cocktail9 ingredient1 ingredient2 shaker1 left right)
(pour-shaker-to-shot cocktail9 shot4 left shaker1 l2 l1)
(grasp right shot12)
(leave left shaker1)
(refill-shot shot12 ingredient2 right left dispenser2)
(grasp left shaker1)
(leave right shot12)
(empty-shaker left shaker1 cocktail9 l1 l0)
(clean-shaker left right shaker1)
(grasp right shot12)
(pour-shot-to-clean-shaker shot12 ingredient2 shaker1 right l0 l1)
(leave left shaker1)
(clean-shot shot12 ingredient2 right left)
(fill-shot shot12 ingredient4 right left dispenser4)
(pour-shot-to-used-shaker shot12 ingredient4 shaker1 right l1 l2)
(clean-shot shot12 ingredient4 right left)
(fill-shot shot12 ingredient2 right left dispenser2)
(grasp left shaker1)
(leave right shot12)
(shake cocktail11 ingredient4 ingredient2 shaker1 left right)
(pour-shaker-to-shot cocktail11 shot3 left shaker1 l2 l1)
(empty-shaker left shaker1 cocktail11 l1 l0)
(clean-shaker left right shaker1)
(grasp right shot15)
(pour-shot-to-clean-shaker shot15 ingredient5 shaker1 right l0 l1)
(leave right shot15)
(grasp right shot14)
(pour-shot-to-used-shaker shot14 ingredient3 shaker1 right l1 l2)
(leave right shot14)
(shake cocktail4 ingredient3 ingredient5 shaker1 left right)
(pour-shaker-to-shot cocktail4 shot1 left shaker1 l2 l1)
(grasp right shot14)
(leave left shaker1)
(refill-shot shot14 ingredient3 right left dispenser3)
(grasp left shaker1)
(empty-shaker left shaker1 cocktail4 l1 l0)
(leave right shot14)
(clean-shaker left right shaker1)
(grasp right shot12)
(pour-shot-to-clean-shaker shot12 ingredient2 shaker1 right l0 l1)
(leave left shaker1)
(clean-shot shot12 ingredient2 right left)
(fill-shot shot12 ingredient1 right left dispenser1)
(pour-shot-to-used-shaker shot12 ingredient1 shaker1 right l1 l2)
(clean-shot shot12 ingredient1 right left)
(fill-shot shot12 ingredient2 right left dispenser2)
(grasp left shaker1)
(leave right shot12)
(shake cocktail2 ingredient2 ingredient1 shaker1 left right)
(pour-shaker-to-shot cocktail2 shot9 left shaker1 l2 l1)
(grasp right shot15)
(leave left shaker1)
(clean-shot shot15 ingredient5 right left)
(fill-shot shot15 ingredient1 right left dispenser1)
(grasp left shot13)
(leave right shot15)
(refill-shot shot13 ingredient3 left right dispenser3)
(grasp right shaker1)
(leave left shot13)
(empty-shaker right shaker1 cocktail2 l1 l0)
(clean-shaker right left shaker1)
(grasp left shot15)
(pour-shot-to-clean-shaker shot15 ingredient1 shaker1 left l0 l1)
(leave right shaker1)
(clean-shot shot15 ingredient1 left right)
(fill-shot shot15 ingredient4 left right dispenser4)
(pour-shot-to-used-shaker shot15 ingredient4 shaker1 left l1 l2)
(clean-shot shot15 ingredient4 left right)
(fill-shot shot15 ingredient5 left right dispenser5)
(grasp right shaker1)
(leave left shot15)
(shake cocktail3 ingredient4 ingredient1 shaker1 right left)
(leave right shaker1)
(grasp right shot11)
(clean-shot shot11 ingredient1 right left)
(grasp left shaker1)
(pour-shaker-to-shot cocktail3 shot11 left shaker1 l2 l1)
(leave right shot11)
(empty-shaker left shaker1 cocktail3 l1 l0)
(clean-shaker left right shaker1)
(grasp right shot15)
(pour-shot-to-clean-shaker shot15 ingredient5 shaker1 right l0 l1)
(leave right shot15)
(grasp right shot12)
(pour-shot-to-used-shaker shot12 ingredient2 shaker1 right l1 l2)
(leave right shot12)
(shake cocktail7 ingredient2 ingredient5 shaker1 left right)
(pour-shaker-to-shot cocktail7 shot2 left shaker1 l2 l1)
(grasp right shot14)
(leave left shaker1)
(grasp left shot15)
(leave right shot14)
(clean-shot shot15 ingredient5 left right)
(fill-shot shot15 ingredient1 left right dispenser1)
(grasp right shaker1)
(empty-shaker right shaker1 cocktail7 l1 l0)
(leave left shot15)
(clean-shaker right left shaker1)
(grasp left shot15)
(pour-shot-to-clean-shaker shot15 ingredient1 shaker1 left l0 l1)
(leave left shot15)
(grasp left shot14)
(pour-shot-to-used-shaker shot14 ingredient3 shaker1 left l1 l2)
(leave left shot14)
(shake cocktail10 ingredient3 ingredient1 shaker1 right left)
(pour-shaker-to-shot cocktail10 shot5 right shaker1 l2 l1)
(leave right shaker1)
(grasp right shot14)
(refill-shot shot14 ingredient3 right left dispenser3)
(leave right shot14)
(grasp right shot12)
(refill-shot shot12 ingredient2 right left dispenser2)