(grasp right shot13)
(fill-shot shot13 ingredient1 right left dispenser1)
(pour-shot-to-clean-shaker shot13 ingredient1 shaker1 right l0 l1)
(clean-shot shot13 ingredient1 right left)
(fill-shot shot13 ingredient4 right left dispenser4)
(pour-shot-to-used-shaker shot13 ingredient4 shaker1 right l1 l2)
(clean-shot shot13 ingredient4 right left)
(fill-shot shot13 ingredient1 right left dispenser1)
(leave right shot13)
(grasp right shaker1)
(shake cocktail9 ingredient1 ingredient4 shaker1 right left)
(pour-shaker-to-shot cocktail9 shot12 right shaker1 l2 l1)
(pour-shaker-to-shot cocktail9 shot1 right shaker1 l1 l0)
(leave right shaker1)
(grasp left shaker1)
(empty-shaker left shaker1 cocktail9 l0 l0)
(clean-shaker left right shaker1)
(grasp right shot13)
(empty-shot right shot13 ingredient1)
(leave left shaker1)
(clean-shot shot13 ingredient1 right left)
(fill-shot shot13 ingredient2 right left dispenser2)
(pour-shot-to-clean-shaker shot13 ingredient2 shaker1 right l0 l1)
(clean-shot shot13 ingredient2 right left)
(fill-shot shot13 ingredient4 right left dispenser4)
(pour-shot-to-used-shaker shot13 ingredient4 shaker1 right l1 l2)
(clean-shot shot13 ingredient4 right left)
(fill-shot shot13 ingredient1 right left dispenser1)
(grasp left shaker1)
(leave right shot13)
(shake cocktail11 ingredient2 ingredient4 shaker1 left right)
(pour-shaker-to-shot cocktail11 shot14 left shaker1 l2 l1)
(pour-shaker-to-shot cocktail11 shot11 left shaker1 l1 l0)
(empty-shaker left shaker1 cocktail11 l0 l0)
(clean-shaker left right shaker1)
(grasp right shot13)
(empty-shot right shot13 ingredient1)
(leave left shaker1)
(clean-shot shot13 ingredient1 right left)
(fill-shot shot13 ingredient3 right left dispenser3)
(grasp left shot15)
(leave right shot13)
(fill-shot shot15 ingredient2 left right dispenser2)
(grasp right shot10)
(leave left shot15)
(fill-shot shot10 ingredient3 right left dispenser3)
(grasp left shot9)
(leave right shot10)
(fill-shot shot9 ingredient1 left right dispenser1)
(pour-shot-to-clean-shaker shot9 ingredient1 shaker1 left l0 l1)
(refill-shot shot9 ingredient1 left right dispenser1)
(grasp right shot8)
(leave left shot9)
(fill-shot shot8 ingredient3 right left dispenser3)
(grasp left shot7)
(leave right shot8)
(fill-shot shot7 ingredient3 left right dispenser3)
(grasp right shot6)
(leave left shot7)
(fill-shot shot6 ingredient2 right left dispenser2)
(grasp left shot5)
(leave right shot6)
(fill-shot shot5 ingredient2 left right dispenser2)
(grasp right shot13)
(pour-shot-to-used-shaker shot13 ingredient3 shaker1 right l1 l2)
(leave left shot5)
(clean-shot shot13 ingredient3 right left)
(fill-shot shot13 ingredient1 right left dispenser1)
(grasp left shot6)
(leave right shot13)
(grasp right shaker1)
(leave left shot6)
(shake cocktail6 ingredient3 ingredient1 shaker1 right left)
(grasp left shot6)
(empty-shot left shot6 ingredient2)
(leave right shaker1)
(clean-shot shot6 ingredient2 left right)
(fill-shot shot6 ingredient4 left right dispenser4)
(grasp right shot8)
(leave left shot6)
(grasp left shaker1)
(empty-shot right shot8 ingredient3)
(leave right shot8)
(empty-shaker left shaker1 cocktail6 l2 l0)
(clean-shaker left right shaker1)
(grasp right shot6)
(pour-shot-to-clean-shaker shot6 ingredient4 shaker1 right l0 l1)
(leave right shot6)
(grasp right shot5)
(pour-shot-to-used-shaker shot5 ingredient2 shaker1 right l1 l2)
(leave right shot5)
(shake cocktail3 ingredient2 ingredient4 shaker1 left right)
(pour-shaker-to-shot cocktail3 shot3 left shaker1 l2 l1)
(grasp right shot8)
(leave left shaker1)
(clean-shot shot8 ingredient3 right left)
(fill-shot shot8 ingredient2 right left dispenser2)
(grasp left shaker1)
(empty-shaker left shaker1 cocktail3 l1 l0)
(leave right shot8)
(clean-shaker left right shaker1)
(grasp right shot10)
(pour-shot-to-clean-shaker shot10 ingredient3 shaker1 right l0 l1)
(leave left shaker1)
(clean-shot shot10 ingredient3 right left)
(fill-shot shot10 ingredient4 right left dispenser4)
(pour-shot-to-used-shaker shot10 ingredient4 shaker1 right l1 l2)
(grasp left shaker1)
(leave right shot10)
(shake cocktail1 ingredient3 ingredient4 shaker1 left right)
(grasp right shot10)
(leave left shaker1)
(refill-shot shot10 ingredient4 right left dispenser4)
(grasp left shot8)
(leave right shot10)
(empty-shot left shot8 ingredient2)
(clean-shot shot8 ingredient2 left right)
(grasp right shaker1)
(pour-shaker-to-shot cocktail1 shot8 right shaker1 l2 l1)
(leave left shot8)
(empty-shaker right shaker1 cocktail1 l1 l0)
(clean-shaker right left shaker1)
(grasp left shot10)
(pour-shot-to-clean-shaker shot10 ingredient4 shaker1 left l0 l1)
(leave left shot10)
(grasp left shot15)
(pour-shot-to-used-shaker shot15 ingredient2 shaker1 left l1 l2)
(leave left shot15)
(shake cocktail7 ingredient4 ingredient2 shaker1 right left)
(pour-shaker-to-shot cocktail7 shot2 right shaker1 l2 l1)
(empty-shaker right shaker1 cocktail7 l1 l0)
(clean-shaker right left shaker1)
(grasp left shot7)
(pour-shot-to-clean-shaker shot7 ingredient3 shaker1 left l0 l1)
(leave right shaker1)
(clean-shot shot7 ingredient3 left right)
(fill-shot shot7 ingredient2 left right dispenser2)
(pour-shot-to-used-shaker shot7 ingredient2 shaker1 left l1 l2)
(grasp right shaker1)
(leave left shot7)
(shake cocktail2 ingredient3 ingredient2 shaker1 right left)
(grasp left shot10)
(leave right shaker1)
(grasp right shot5)
(leave left shot10)
(clean-shot shot5 ingredient2 right left)
(grasp left shaker1)
(pour-shaker-to-shot cocktail2 shot5 left shaker1 l2 l1)
(leave right shot5)
(grasp right shot10)
(leave left shaker1)
(clean-shot shot10 ingredient4 right left)
(grasp left shot7)
(leave right shot10)
(clean-shot shot7 ingredient2 left right)
(grasp right shaker1)
(leave left shot7)
(grasp left shot6)
(leave right shaker1)
(refill-shot shot6 ingredient4 left right dispenser4)
(grasp right shaker1)
(empty-shaker right shaker1 cocktail2 l1 l0)
(leave left shot6)
(clean-shaker right left shaker1)
(grasp left shot6)
(pour-shot-to-clean-shaker shot6 ingredient4 shaker1 left l0 l1)
(leave right shaker1)
(clean-shot shot6 ingredient4 left right)
(fill-shot shot6 ingredient2 left right dispenser2)
(pour-shot-to-used-shaker shot6 ingredient2 shaker1 left l1 l2)
(grasp right shaker1)
(leave left shot6)
(shake cocktail8 ingredient2 ingredient4 shaker1 right left)
(pour-shaker-to-shot cocktail8 shot4 right shaker1 l2 l1)
(empty-shaker right shaker1 cocktail8 l1 l0)
(clean-shaker right left shaker1)
(grasp left shot13)
(pour-shot-to-clean-shaker shot13 ingredient1 shaker1 left l0 l1)
(leave right shaker1)
(clean-shot shot13 ingredient1 left right)
(fill-shot shot13 ingredient3 left right dispenser3)
(pour-shot-to-used-shaker shot13 ingredient3 shaker1 left l1 l2)
(clean-shot shot13 ingredient3 left right)
(fill-shot shot13 ingredient1 left right dispenser1)
(grasp right shot15)
(leave left shot13)
(refill-shot shot15 ingredient2 right left dispenser2)
(grasp left shaker1)
(leave right shot15)
(shake cocktail6 ingredient3 ingredient1 shaker1 left right)
(pour-shaker-to-shot cocktail6 shot10 left shaker1 l2 l1)
(grasp right shot9)
(leave left shaker1)
(grasp left shot15)
(empty-shot left shot15 ingredient2)
(leave right shot9)
(clean-shot shot15 ingredient2 left right)
(grasp right shaker1)
(pour-shaker-to-shot cocktail6 shot15 right shaker1 l1 l0)
(empty-shaker right shaker1 cocktail6 l0 l0)
(leave left shot15)
(clean-shaker right left shaker1)
(grasp left shot7)
(leave right shaker1)
(fill-shot shot7 ingredient2 left right dispenser2)
(pour-shot-to-clean-shaker shot7 ingredient2 shaker1 left l0 l1)
(clean-shot shot7 ingredient2 left right)
(fill-shot shot7 ingredient3 left right dispenser3)
(pour-shot-to-used-shaker shot7 ingredient3 shaker1 left l1 l2)
(grasp right shaker1)
(leave left shot7)
(shake cocktail10 ingredient2 ingredient3 shaker1 right left)
(grasp left shot7)
(leave right shaker1)
(clean-shot shot7 ingredient3 left right)
(grasp right shaker1)
(pour-shaker-to-shot cocktail10 shot7 right shaker1 l2 l1)
(leave left shot7)
(grasp left shot9)
(empty-shot left shot9 ingredient1)
(leave right shaker1)
(clean-shot shot9 ingredient1 left right)
(grasp right shaker1)
(empty-shaker right shaker1 cocktail10 l1 l0)
(leave left shot9)
(clean-shaker right left shaker1)
(grasp left shot9)
(leave right shaker1)
(fill-shot shot9 ingredient2 left right dispenser2)
(pour-shot-to-clean-shaker shot9 ingredient2 shaker1 left l0 l1)
(clean-shot shot9 ingredient2 left right)
(fill-shot shot9 ingredient4 left right dispenser4)
(pour-shot-to-used-shaker shot9 ingredient4 shaker1 left l1 l2)
(leave left shot9)
(grasp left shaker1)
(shake cocktail5 ingredient4 ingredient2 shaker1 left right)
(grasp right shot9)
(leave left shaker1)
(clean-shot shot9 ingredient4 right left)
(grasp left shaker1)
(pour-shaker-to-shot cocktail5 shot9 left shaker1 l2 l1)
(leave right shot9)
(empty-shaker left shaker1 cocktail5 l1 l0)
(clean-shaker left right shaker1)
(grasp right shot13)
(leave left shaker1)
(grasp left shot6)
(leave right shot13)
(clean-shot shot6 ingredient2 left right)
(fill-shot shot6 ingredient3 left right dispenser3)
(pour-shot-to-clean-shaker shot6 ingredient3 shaker1 left l0 l1)
(clean-shot shot6 ingredient3 left right)
(fill-shot shot6 ingredient4 left right dispenser4)
(pour-shot-to-used-shaker shot6 ingredient4 shaker1 left l1 l2)
(leave left shot6)
(grasp left shaker1)
(shake cocktail4 ingredient4 ingredient3 shaker1 left right)
(leave left shaker1)
(grasp left shot6)
(clean-shot shot6 ingredient4 left right)
(grasp right shaker1)
(pour-shaker-to-shot cocktail4 shot6 right shaker1 l2 l1)