(grasp right shot12)
(fill-shot shot12 ingredient3 right left dispenser3)
(pour-shot-to-clean-shaker shot12 ingredient3 shaker1 right l0 l1)
(clean-shot shot12 ingredient3 right left)
(fill-shot shot12 ingredient1 right left dispenser1)
(pour-shot-to-used-shaker shot12 ingredient1 shaker1 right l1 l2)
(clean-shot shot12 ingredient1 right left)
(fill-shot shot12 ingredient3 right left dispenser3)
(leave right shot12)
(grasp right shaker1)
(shake cocktail1 ingredient3 ingredient1 shaker1 right left)
(pour-shaker-to-shot cocktail1 shot8 right shaker1 l2 l1)
(empty-shaker right shaker1 cocktail1 l1 l0)
(clean-shaker right left shaker1)
(grasp left shot12)
(pour-shot-to-clean-shaker shot12 ingredient3 shaker1 left l0 l1)
(leave right shaker1)
(clean-shot shot12 ingredient3 left right)
(fill-shot shot12 ingredient1 left right dispenser1)
(pour-shot-to-used-shaker shot12 ingredient1 shaker1 left l1 l2)
(clean-shot shot12 ingredient1 left right)
(fill-shot shot12 ingredient3 left right dispenser3)
(grasp right shot13)
(leave left shot12)
(grasp left shaker1)
(leave right shot13)
(shake cocktail3 ingredient1 ingredient3 shaker1 left right)
(leave left shaker1)
(grasp left shot11)
(fill-shot shot11 ingredient1 left right dispenser1)
(grasp right shaker1)
(pour-shaker-to-shot cocktail3 shot7 right shaker1 l2 l1)
(leave left shot11)
(grasp left shot10)
(leave right shaker1)
(fill-shot shot10 ingredient4 left right dispenser4)
(grasp right shaker1)
(empty-shaker right shaker1 cocktail3 l1 l0)
(leave left shot10)
(clean-shaker right left shaker1)
(grasp left shot11)
(pour-shot-to-clean-shaker shot11 ingredient1 shaker1 left l0 l1)
(leave right shaker1)
(clean-shot shot11 ingredient1 left right)
(fill-shot shot11 ingredient2 left right dispenser2)
(pour-shot-to-used-shaker shot11 ingredient2 shaker1 left l1 l2)
(grasp right shaker1)
(leave left shot11)
(shake cocktail5 ingredient1 ingredient2 shaker1 right left)
(pour-shaker-to-shot cocktail5 shot2 right shaker1 l2 l1)
(empty-shaker right shaker1 cocktail5 l1 l0)
(clean-shaker right left shaker1)
(grasp left shot10)
(pour-shot-to-clean-shaker shot10 ingredient4 shaker1 left l0 l1)
(leave right shaker1)
(clean-shot shot10 ingredient4 left right)
(fill-shot shot10 ingredient1 left right dispenser1)
(pour-shot-to-used-shaker shot10 ingredient1 shaker1 left l1 l2)
(grasp right shaker1)
(leave left shot10)
(shake cocktail10 ingredient1 ingredient4 shaker1 right left)
(pour-shaker-to-shot cocktail10 shot3 right shaker1 l2 l1)
(grasp left shot11)
(leave right shaker1)
(clean-shot shot11 ingredient2 left right)
(grasp right shaker1)
(pour-shaker-to-shot cocktail10 shot11 right shaker1 l1 l0)
(leave left shot11)
(empty-shaker right shaker1 cocktail10 l0 l0)
(clean-shaker right left shaker1)
(grasp left shot13)
(leave right shaker1)
(fill-shot shot13 ingredient1 left right dispenser1)
(pour-shot-to-clean-shaker shot13 ingredient1 shaker1 left l0 l1)
(clean-shot shot13 ingredient1 left right)
(fill-shot shot13 ingredient4 left right dispenser4)
(pour-shot-to-used-shaker shot13 ingredient4 shaker1 left l1 l2)
(leave left shot13)
(grasp left shaker1)
(shake cocktail6 ingredient4 ingredient1 shaker1 left right)
(pour-shaker-to-shot cocktail6 shot6 left shaker1 l2 l1)
(grasp right shot12)
(empty-shot right shot12 ingredient3)
(leave right shot12)
(grasp right shot9)
(leave left shaker1)
(fill-shot shot9 ingredient3 right left dispenser3)
(grasp left shaker1)
(empty-shaker left shaker1 cocktail6 l1 l0)
(leave right shot9)
(clean-shaker left right shaker1)
(grasp right shot5)
(leave left shaker1)
(fill-shot shot5 ingredient1 right left dispenser1)
(pour-shot-to-clean-shaker shot5 ingredient1 shaker1 right l0 l1)
(clean-shot shot5 ingredient1 right left)
(fill-shot shot5 ingredient4 right left dispenser4)
(grasp left shot9)
(pour-shot-to-used-shaker shot9 ingredient3 shaker1 left l1 l2)
(leave right shot5)
(clean-shot shot9 ingredient3 left right)
(fill-shot shot9 ingredient2 left right dispenser2)
(grasp right shaker1)
(leave left shot9)
(shake cocktail8 ingredient3 ingredient1 shaker1 right left)
(pour-shaker-to-shot cocktail8 shot4 right shaker1 l2 l1)
(grasp left shot12)
(leave right shaker1)
(refill-shot shot12 ingredient3 left right dispenser3)
(grasp right shaker1)
(empty-shaker right shaker1 cocktail8 l1 l0)
(leave left shot12)
(clean-shaker right left shaker1)
(grasp left shot9)
(pour-shot-to-clean-shaker shot9 ingredient2 shaker1 left l0 l1)
(leave right shaker1)
(clean-shot shot9 ingredient2 left right)
(fill-shot shot9 ingredient1 left right dispenser1)
(pour-shot-to-used-shaker shot9 ingredient1 shaker1 left l1 l2)
(grasp right shaker1)
(leave left shot9)
(shake cocktail9 ingredient2 ingredient1 shaker1 right left)
(grasp left shot5)
(empty-shot left shot5 ingredient4)
(leave right shaker1)
(clean-shot shot5 ingredient4 left right)
(grasp right shaker1)
(pour-shaker-to-shot cocktail9 shot5 right shaker1 l2 l1)
(leave left shot5)
(empty-shaker right shaker1 cocktail9 l1 l0)
(clean-shaker right left shaker1)
(grasp left shot13)
(leave right shaker1)
(refill-shot shot13 ingredient4 left right dispenser4)
(pour-shot-to-clean-shaker shot13 ingredient4 shaker1 left l0 l1)
(clean-shot shot13 ingredient4 left right)
(fill-shot shot13 ingredient1 left right dispenser1)
(pour-shot-to-used-shaker shot13 ingredient1 shaker1 left l1 l2)
(leave left shot13)
(grasp left shaker1)
(shake cocktail7 ingredient1 ingredient4 shaker1 left right)
(grasp right shot10)
(leave left shaker1)
(clean-shot shot10 ingredient1 right left)
(grasp left shaker1)
(leave right shot10)
(grasp right shot9)
(leave left shaker1)
(clean-shot shot9 ingredient1 right left)
(grasp left shaker1)
(pour-shaker-to-shot cocktail7 shot9 left shaker1 l2 l1)
(leave right shot9)
(empty-shaker left shaker1 cocktail7 l1 l0)
(clean-shaker left right shaker1)
(grasp right shot12)
(pour-shot-to-clean-shaker shot12 ingredient3 shaker1 right l0 l1)
(leave left shaker1)
(refill-shot shot12 ingredient3 right left dispenser3)
(grasp left shot1)
(leave right shot12)
(fill-shot shot1 ingredient2 left right dispenser2)
(pour-shot-to-used-shaker shot1 ingredient2 shaker1 left l1 l2)
(grasp right shaker1)
(leave left shot1)
(shake cocktail4 ingredient3 ingredient2 shaker1 right left)
(grasp left shot12)
(empty-shot left shot12 ingredient3)
(leave right shaker1)
(clean-shot shot12 ingredient3 left right)
(fill-shot shot12 ingredient2 left right dispenser2)
(grasp right shot10)
(leave left shot12)
(grasp left shot1)
(leave right shot10)
(clean-shot shot1 ingredient2 left right)
(grasp right shaker1)
(pour-shaker-to-shot cocktail4 shot1 right shaker1 l2 l1)
(leave left shot1)
(empty-shaker right shaker1 cocktail4 l1 l0)
(clean-shaker right left shaker1)
(grasp left shot12)
(pour-shot-to-clean-shaker shot12 ingredient2 shaker1 left l0 l1)
(leave right shaker1)
(grasp right shot10)
(leave left shot12)
(fill-shot shot10 ingredient3 right left dispenser3)
(pour-shot-to-used-shaker shot10 ingredient3 shaker1 right l1 l2)
(grasp left shaker1)
(leave right shot10)
(shake cocktail4 ingredient3 ingredient2 shaker1 left right)
(empty-shaker left shaker1 cocktail4 l2 l0)
(clean-shaker left right shaker1)
(grasp right shot13)
(leave left shaker1)
(clean-shot shot13 ingredient1 right left)
(fill-shot shot13 ingredient4 right left dispenser4)
(pour-shot-to-clean-shaker shot13 ingredient4 shaker1 right l0 l1)
(clean-shot shot13 ingredient4 right left)
(fill-shot shot13 ingredient3 right left dispenser3)
(pour-shot-to-used-shaker shot13 ingredient3 shaker1 right l1 l2)
(grasp left shot10)
(leave right shot13)
(grasp right shaker1)
(leave left shot10)
(shake cocktail2 ingredient4 ingredient3 shaker1 right left)
(leave right shaker1)
(grasp right shot12)
(clean-shot shot12 ingredient2 right left)
(fill-shot shot12 ingredient3 right left dispenser3)
(leave right shot12)
(grasp right shot10)
(clean-shot shot10 ingredient3 right left)
(grasp left shaker1)
(pour-shaker-to-shot cocktail2 shot10 left shaker1 l2 l1)